### ISSUE TITLE
FSCONTACT - Gestão de BDs / Analytics / CRM

### ISSUE THREAD

**Issue by vitorhmcorreia** [RicardoJSTeixeira/ducking-octo-ironman#4]
- Só é possível usar o CRM ou o Analytics sobre BDs activas

**Comment by RicardoJSTeixeira** [comment]
É verdade :-(

**Comment by vitorhmcorreia** [comment]
Estão a questionar-me se será implementada a funcionalidade para BDs desactivadas.

**Comment by RicardoJSTeixeira** [comment]
Isto já está como pretendem, confirmas?

**Comment by vitorhmcorreia** [comment]
Confirmo.
