### ISSUE TITLE
Gravar negativos

### ISSUE THREAD

**Issue by vitorhmcorreia** [RicardoJSTeixeira/ducking-octo-ironman#6]
Em DEV, tenho um botão para gravar negativos, aka, tudo o que não é vendas, com os dados preenchidos ou não.

A questão prende-se com só ter os dados completos no app6, mas o botão está disponível no header e ao mandar executar, o oDados está fora de scope.

Como farias? Sei que tinhas me falado de uma forma, mas acabamos por nunca elaborar o assunto.

**Comment by RicardoJSTeixeira** [comment]
A minha ideia é enviar uma mensagem de fecho de chamada para correres o save automaticamente. Mas tenho de o implementar ainda :-|. Até lá está tua solução é o ideal workaround.

**Comment by vitorhmcorreia** [comment]
Ok
